[types]
"Blog Post" = "https://schema.org/BlogPosting"
"Article" = "https://schema.org/Article"
"Web Page" = "https://schema.org/WebPage"

[properties]
title = "https://schema.org/name"
author = "https://schema.org/author"
date = "https://schema.org/datePublished"
description = "https://schema.org/description"
tags = "https://schema.org/keywords"
