[types]
"Documentation" = "https://schema.org/TechArticle"
"Guide" = "https://schema.org/HowTo"
"Web Page" = "https://schema.org/WebPage"

[properties]
title = "https://schema.org/name"
author = "https://schema.org/author"
date = "https://schema.org/datePublished"
description = "https://schema.org/description"
